server {
    listen       __REPLACE_PORT__;
    server_name  localhost;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /health_check {
        add_header Content-Type text/plain;
        return 200 'nginx OK';
    }

    location /health {
        add_header Content-Type text/plain;
        return 200 'nginx OK';
    }

    location /healthz {
        add_header Content-Type text/plain;
        return 200 'nginx OK';
    }
    
    location /livez {
        add_header Content-Type text/plain;
        return 200 'nginx OK';
    }

    location /up {
        add_header Content-Type text/plain;
        return 200 'nginx OK';
    }

    error_page   500 502 503 504  /50x.html;

    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}