server {
    listen       __REPLACE_PORT__;
    server_name  localhost;

    location /health_check {
        add_header Content-Type text/plain;
        return 200 'nginx OK';
    }

    location /health {
        add_header Content-Type text/plain;
        return 200 'nginx OK';
    }

    location /healthz {
        add_header Content-Type text/plain;
        return 200 'nginx OK';
    }
    
    location /livez {
        add_header Content-Type text/plain;
        return 200 'nginx OK';
    }

    location /up {
        add_header Content-Type text/plain;
        return 200 'nginx OK';
    }

    location /version {
        add_header Content-Type text/html;
        return 200 '<h1> This is __REPLACE_ENV__ stack</h1>';
    }

}
